### ISSUE TITLE
Some style rules generated by WP for block-markup aren't in the Next.js app

### ISSUE THREAD

**Issue by MichaelAllenWarner** [utkwdn/utk-atlas#101]
Some style-rules for block-markup in the Plugin repo don't have counterparts in the Next.js app (or in the framework). For example, this rule:

```css
.has-white-color {
    color: var(--wp--preset--color--white) !important;
}
```

Not sure what the best approach is yet, but we'll have to account for these styles one way or another.
